### ISSUE TITLE
Python 3.12 compatability

### ISSUE THREAD

**Issue by MaxAvonic** [balena-io/balena-sdk-python#347] opened 2023-10-03 14:49 UTC
We were using the latest python version for our docker version and this updated to 3.12 today.
While building a new release as of now, we came across this issue. 
We do not have this issue when building our image with python 3.11

![image](https://github.com/balena-io/balena-sdk-python/assets/114392598/a78f7bef-28e6-4e7c-9c05-4d97d4fce390)

**Comment by otaviojacobi** [comment] 2023-10-12 00:19
Hello @MaxAvonic thanks for raising but I could not reproduce. I created a empty conda environement with python 3.12.0 installed, ran a clean `pip install balena-sdk` from scratch and ran our test suite and manually tested a basic example and everything worked. More over, I ran our CI with Python 3.12 and everything is fine: https://github.com/balena-io/balena-sdk-python/pull/348

Now looking at your error I see it is caused because a bug on a version of the typing_extensions library which was already fixed on https://github.com/python/typing_extensions/pull/162 and on our SDK we defined this library version as "*" [here](https://github.com/balena-io/balena-sdk-python/blob/master/pyproject.toml#L19), which means, any version. I suspect that in your build process some other library or some caching is setting this library aswell using an outdated version that has the bug, could you please ensure you set `typing_extensions` library to latest and check if it works?

**Closed as completed** 2023-11-21 14:30 UTC
